#!/bin/bash

# ./helm repo add gitlab https://charts.gitlab.io
# ./helm init


./helm install \
  --namespace gitlab-runner \
  --name gitlab-runner \
  -f ./values.yaml \
  ./charts/gitlab-runner

./helm upgrade gitlab-runner \
  --set gitlabUrl=$GITLAB_CI_URL,runnerRegistrationToken=$GITLAB_CI_TOKEN \
  ./charts/gitlab-runner
